spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: test_route0
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
  application:
    name: guli-gateway
server:
  port: 8088

